youtube.com/dotNET Microservices by Julio Casal/Playstore/Playstore.Client/Models/Inventory/InventoryItemViewModel.cs
namespace Playstore.Client.Models.Inventory;

/// <summary>View model vor an inventory item.</summary>
public class InventoryItemViewModel
{
    /// <summary>ID of the item in the catalog.</summary>
    public Guid Id { get; set; }

    /// <summary>Item name.</summary>
    public string Name { get; set; }

    /// <summary>Item description.</summary>
    public string Description { get; set; }

    /// <summary>Item quantity.</summary>
    public int Quantity { get; set; }
}

youtube.com/dotNET Microservices by Julio Casal/Playstore/Playstore.Client/Models/Inventory/PurchaseItemViewModel.cs
using System.ComponentModel.DataAnnotations;
using Playstore.Client.Models.Catalog;

namespace Playstore.Client.Models.Inventory;

/// <summary>View model for purchasing items.</summary>
public class PurchaseItemViewModel : CatalogItemViewModel
{
    /// <summary>How many items to purchase.</summary>
    [Range(1, 100)]
    public int Quantity { get; set; }
}

youtube.com/dotNET Microservices by Julio Casal/Playstore/Playstore.Client/Controllers/InventoryController.cs
using System.IdentityModel.Tokens.Jwt;
using System.Net;
using MassTransit.Initializers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Playstore.Catalog.Contracts.DataTransferObjects;
using Playstore.Client.Models;
using Playstore.Client.Models.Catalog;
using Playstore.Client.Models.Inventory;
using Playstore.Client.ServiceClients;
using Playstore.Inventory.Contracts.DataTransferObjects;

namespace Playstore.Client.Controllers;

/// <summary>Operations with inventory items.</summary>
[Authorize(Roles = "Player")]
public class InventoryController : Controller
{
    /// <summary>Client for communicating with the catalog service.</summary>
    private readonly ICatalogClient _catalogClient;

    /// <summary>Client for communicating with the inventory service.</summary>
    private readonly IInventoryClient _inventoryClient;

    public InventoryController(IInventoryClient inventoryClient, ICatalogClient catalogClient)
    {
        _inventoryClient = inventoryClient;
        _catalogClient = catalogClient;
    }

    /// <summary>Lists the items in the inventory.</summary>
    /// <returns>Inventory/Index page.</returns>
    [HttpGet]
    public async Task<IActionResult> IndexAsync()
    {
        IReadOnlyCollection<InventoryItemDto> inventoryItems = await _inventoryClient.GetItemsAsync(GetCurrentUserId());
        IEnumerable<InventoryItemViewModel> items = inventoryItems
            .Select(dto =>  new InventoryItemViewModel
            {
                Id = dto.CatalogItemId,
                Name = dto.Name,
                Description = dto.Description,
                Quantity = dto.Quantity
            });

        return View(items);
    }

    /// <summary>Lists catalog items for purchase.</summary>
    /// <returns>Inventory/Purchase page.</returns>
    [HttpGet]
    public async Task<IActionResult> PurchaseAsync()
    {
        IReadOnlyCollection<CatalogItemDto> catalogItems = await _catalogClient.GetAllItemsAsync();
        IEnumerable<CatalogItemViewModel> items = catalogItems
            .Select(dto => new CatalogItemViewModel
            {
                Id = dto.Id,
                Name = dto.Name,
                Description = dto.Description,
                Price = dto.Price
            });

        return View(items);
    }

    /// <summary>Page for purchasing an item.</summary>
    /// <param name="id">ID of the item in the catalog.</param>
    /// <returns>Inventory/PurchaseItem page.</returns>
    [HttpGet]
    public async Task<IActionResult> PurchaseItemAsync(Guid? id)
    {
        if (!id.HasValue)
        {
            return NotFound();
        }

        try
        {
            CatalogItemDto item = await _catalogClient.GetItemAsync(id.Value);
            return View(new PurchaseItemViewModel
            {
                Id = item.Id,
                Name = item.Name,
                Description = item.Description,
                Price = item.Price
            });
        }
        catch (HttpRequestException exception)
        {
            if (exception.StatusCode == HttpStatusCode.NotFound)
            {
                return NotFound();
            }

            TempData[NotificationsViewModel.c_Error] = "An error has occured on the server";
            return RedirectToAction("Index");
        }
    }

    /// <summary>Purchase an item.</summary>
    /// <param name="item">The item to purchase.</param>
    /// <returns>Redirects to Inventory/Index page.</returns>
    [HttpPost]
    public async Task<IActionResult> PurchaseItemAsync(PurchaseItemViewModel item)
    {
        if (ModelState.IsValid)
        {
            await _inventoryClient.GrantInventoryItems(new GrantInventoryItemsDto(GetCurrentUserId(), item.Id, item.Quantity));
            TempData[NotificationsViewModel.c_Success] = "Items purchased successfully";
            return RedirectToAction("Index");
        }
        else
        {
            return View(item);
        }
    }

    private Guid GetCurrentUserId()
    {
        var userId = User.Claims.Single(claim => claim.Type == JwtRegisteredClaimNames.Sub).Value;
        return new Guid(userId);
    }
}

youtube.com/dotNET Microservices by Julio Casal/Playstore/Playstore.Client/Views/Inventory/Index.cshtml
@using Playstore.Client.Models.Inventory;
@model IEnumerable<InventoryItemViewModel>;
@{
    ViewData["Title"] = "Inventory items";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">@ViewData["Title"]</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-asp-controller="Inventory" asp-action="Purchase" class="btn btn-primary">
                <i class="bi bi-cart"></i>
                Purchase items
            </a>
        </div>
    </div>

    <table class="table table-bordered table-striped" style="width: 100%;">
        <thead>
            <tr>
                <th width="20%">Name</th>
                <th width="50%">Description</th>
                <th width="10%">Quantity</th>
            </tr>
        </thead>
        <tbody>
            @foreach (InventoryItemViewModel item in Model)
            {
                <tr>
                    <td>@item.Name</td>
                    <td>@item.Description</td>
                    <td>@item.Quantity</td>
                </tr>
            }
        </tbody>
    </table>
</div>

youtube.com/dotNET Microservices by Julio Casal/Playstore/Playstore.Client/Views/Inventory/Purchase.cshtml
@using Playstore.Client.Models.Catalog;
@model IEnumerable<CatalogItemViewModel>;
@{
    ViewData["Title"] = "Catalog";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">@ViewData["Title"]</h2>
        </div>
    </div>

    <table class="table table-bordered table-striped" style="width: 100%;">
        <thead>
            <tr>
                <th width="20%">Name</th>
                <th width="50%">Description</th>
                <th width="10%">Price</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (CatalogItemViewModel item in Model)
            {
                <tr>
                    <td>@item.Name</td>
                    <td>@item.Description</td>
                    <td>@item.Price</td>
                    <td>
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="Inventory" asp-action="PurchaseItem" asp-route-id=@item.Id class="btn btn-primary mx-2">
                                <i class="bi bi-cart"></i>
                                Purchase
                            </a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <a asp-controller="Inventory" asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>

youtube.com/dotNET Microservices by Julio Casal/Playstore/Playstore.Client/Views/Inventory/PurchaseItem.cshtml
@using Playstore.Client.Models.Inventory;
@model PurchaseItemViewModel;
@{
    ViewData["Title"] = "Purchase item";
}

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">@ViewData["Title"]</h2>
            <hr />
        </div>
        @* Disabled fields not sent in form. Adding hidden fields. *@
        <input asp-for="Name" hidden />
        <input asp-for="Description" hidden />
        <input asp-for="Price" hidden />
        <div class="mb-3">
            <label asp-for="Name">Name</label>
            <input asp-for="Name" class="form-control" disabled />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Description">Description</label>
            <input asp-for="Description" class="form-control" disabled />
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Price">Price</label>
            <input asp-for="Price" class="form-control" disabled />
            <span asp-validation-for="Price" class="text-danger"></span>
        </div>
        <div class="mb3">
            <label asp-for="Quantity">Quantity</label>
            <input asp-for="Quantity" class="form-control" />
            <span asp-validation-for="Quantity" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary">Purchase</button>
        <a asp-controller="Inventory" asp-action="Purchase" class="btn btn-secondary">Back to List</a>
</form>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}